unittests:
	hla -@@ -p:temp -obj:temp -x:fgetc.exe fgetc
	fgetc.exe
	hla -@@ -p:temp -obj:temp -x:fagets.exe fagets
	fagets.exe
	hla -@@ -p:temp -obj:temp -x:fgetf.exe fgetf
	fgetf.exe
	hla -@@ -p:temp -obj:temp -x:fgethex.exe fgethex
	fgethex.exe
	hla -@@ -p:temp -obj:temp -x:fgeti.exe fgeti
	fgeti.exe
	hla -@@ -p:temp -obj:temp -x:fgeti64.exe fgeti64
	fgeti64.exe
	hla -@@ -p:temp -obj:temp -x:fgeti128.exe fgeti128
	fgeti128.exe
	hla -@@ -p:temp -obj:temp -x:fgetu.exe fgetu
	fgetu.exe
	hla -@@ -p:temp -obj:temp -x:fgetu64.exe fgetu64
	fgetu64.exe
	hla -@@ -p:temp -obj:temp -x:fgetu128.exe fgetu128
	fgetu128.exe

	hla -@@ -p:temp -obj:temp -x:fputhex.exe fputhex
	fputhex.exe
	hlacmp fputhex.data fputhex.txt

	hla -@@ -p:temp -obj:temp -x:fputu.exe fputu
	fputu.exe
	hlacmp fputu.data fputu.txt

	hla -@@ -p:temp -obj:temp -x:fputi.exe fputi
	fputi.exe
	hlacmp fputi.data fputi.txt

	hla -@@ -p:temp -obj:temp -x:fputbool.exe fputbool
	fputbool.exe
	hlacmp fputbool.data fputbool.txt

	hla -@@ -p:temp -obj:temp -x:fputcset.exe fputcset
	fputcset.exe
	hlacmp fputcset.data fputcset.txt

	hla -@@ -p:temp -obj:temp -x:fpute.exe fpute
	fpute.exe
	hlacmp fpute.data fpute.txt

	hla -@@ -p:temp -obj:temp -x:fputr.exe fputr
	fputr.exe
	hlacmp fputr.data fputr.txt




	

thread:
	hla -@@ -thread -p:temp -obj:temp -x:fgetc.exe fgetc
	fgetc.exe
	hla -@@ -thread -p:temp -obj:temp -x:fagets.exe fagets
	fagets.exe
	hla -@@ -thread -p:temp -obj:temp -x:fgetf.exe fgetf
	fgetf.exe
	hla -@@ -thread -p:temp -obj:temp -x:fgethex.exe fgethex
	fgethex.exe
	hla -@@ -thread -p:temp -obj:temp -x:fgeti.exe fgeti
	fgeti.exe
	hla -@@ -thread -p:temp -obj:temp -x:fgeti64.exe fgeti64
	fgeti64.exe
	hla -@@ -thread -p:temp -obj:temp -x:fgeti128.exe fgeti128
	fgeti128.exe
	hla -@@ -thread -p:temp -obj:temp -x:fgetu.exe fgetu
	fgetu.exe
	hla -@@ -thread -p:temp -obj:temp -x:fgetu64.exe fgetu64
	fgetu64.exe
	hla -@@ -thread -p:temp -obj:temp -x:fgetu128.exe fgetu128
	fgetu128.exe

	hla -@@ -thread -p:temp -obj:temp -x:fputhex.exe fputhex
	fputhex.exe
	hlacmp fputhex.data fputhex.txt

	hla -@@ -thread -p:temp -obj:temp -x:fputu.exe fputu
	fputu.exe
	hlacmp fputu.data fputu.txt

	hla -@@ -thread -p:temp -obj:temp -x:fputi.exe fputi
	fputi.exe
	hlacmp fputi.data fputi.txt

	hla -@@ -thread -p:temp -obj:temp -x:fputbool.exe fputbool
	fputbool.exe
	hlacmp fputbool.data fputbool.txt

	hla -@@ -thread -p:temp -obj:temp -x:fputcset.exe fputcset
	fputcset.exe
	hlacmp fputcset.data fputcset.txt

	hla -@@ -thread -p:temp -obj:temp -x:fpute.exe fpute
	fpute.exe
	hlacmp fpute.data fpute.txt

	hla -@@ -thread -p:temp -obj:temp -x:fputr.exe fputr
	fputr.exe
	hlacmp fputr.data fputr.txt




	

clean:
	delete temp
	delete .inc
	delete .o
	delete .obj
	delete .link
	delete .exe
	delete .asm
	delete .txt
	delete .pdb
	delete .ilk
	