all:
	hla -@@ -p:temp -obj:temp -x:tArrays.exe tArrays
	tArrays.exe

thread:
	hla -@@ -p:temp -obj:temp -x:tArrays.exe -thread tArrays
	tArrays.exe

clean:
	delete temp
	delete .inc
	delete .o
	delete .obj
	delete .link
	delete .exe
	delete .asm
	delete .pdb
	delete .ilk
	