all:
	hla -@@ -p:temp -obj:temp tArgs
	tArgs

thread:
	hla -@@ -p:temp -obj:temp -thread tArgs
	tArgs

clean:
	delete tArgs
	delete temp
	delete .inc
	delete .o
	delete .obj
	delete .link
	delete .exe
	delete .asm
	delete .pdb
	delete .ilk
	