all:
	hla -@@ -p:temp -obj:temp -x:tOSFileIO.exe tOSFileIO
	tOSFileIO.exe
	
thread:
	hla -@@ -thread -p:temp -obj:temp -x:tOSFileIO.exe tOSFileIO
	tOSFileIO.exe
	
clean:
	delete temp
	delete .inc
	delete .txt
	delete .o
	delete .obj
	delete .link
	delete .exe
	delete .asm
	delete .pdb
	delete .ilk
	