all:
	hla -@@ -p:temp -obj:temp -x:tTimer.exe tTimer.hla
	tTimer.exe

thread:	 
	hla -@@ -thread -p:temp -obj:temp -x:tTimer.exe tTimer.hla
	tTimer.exe

clean:
	delete temp
	delete .inc
	delete .o
	delete .obj
	delete .link
	delete .exe
	delete .asm
	delete .pdb
	delete .ilk
	