all:
	hla -@@ -p:temp -obj:temp -x:tConsole.exe tConsole.hla
	tConsole.exe
	

thread:
	hla -@@ -thread -p:temp -obj:temp -x:tConsole.exe tConsole.hla
	tConsole.exe
	

clean:
	delete temp
	delete .inc
	delete .o
	delete .obj
	delete .link
	delete .exe
	delete .asm
	delete .pdb
	delete .ilk
