all:
	hla -@@ -p:temp -obj:temp -x:tCoroutines.exe tCoroutines.hla
	tCoroutines.exe

thread:
	hla -@@ -thread -p:temp -obj:temp -x:tCoroutines.exe tCoroutines.hla
	tCoroutines.exe

clean:
	delete temp
	delete .inc
	delete .o
	delete .obj
	delete .link
	delete .exe
	delete .asm
	delete .pdb
	delete .ilk
	