unittests:
	hla -@@ -p:temp -obj:temp -x:fc_getc.exe fc_getc
	fc_getc.exe
	hla -@@ -p:temp -obj:temp -x:fc_agets.exe fc_agets
	fc_agets.exe
	hla -@@ -p:temp -obj:temp -x:fc_getf.exe fc_getf
	fc_getf.exe
	hla -@@ -p:temp -obj:temp -x:fc_gethex.exe fc_gethex
	fc_gethex.exe
	hla -@@ -p:temp -obj:temp -x:fc_geti.exe fc_geti
	fc_geti.exe
	hla -@@ -p:temp -obj:temp -x:fc_geti64.exe fc_geti64
	fc_geti64.exe
	hla -@@ -p:temp -obj:temp -x:fc_geti128.exe fc_geti128
	fc_geti128.exe
	hla -@@ -p:temp -obj:temp -x:fc_getu.exe fc_getu
	fc_getu.exe
	hla -@@ -p:temp -obj:temp -x:fc_getu64.exe fc_getu64
	fc_getu64.exe
	hla -@@ -p:temp -obj:temp -x:fc_getu128.exe fc_getu128
	fc_getu128.exe

	hla -@@ -p:temp -obj:temp -x:fc_puthex.exe fc_puthex
	fc_puthex.exe
	hlacmp fc_puthex.data fc_puthex.txt

	hla -@@ -p:temp -obj:temp -x:fc_putu.exe fc_putu
	fc_putu.exe
	hlacmp fc_putu.data fc_putu.txt

	hla -@@ -p:temp -obj:temp -x:fc_puti.exe fc_puti
	fc_puti.exe
	hlacmp fc_puti.data fc_puti.txt

	hla -@@ -p:temp -obj:temp -x:fc_putbool.exe fc_putbool
	fc_putbool.exe
	hlacmp fc_putbool.data fc_putbool.txt

	hla -@@ -p:temp -obj:temp -x:fc_putcset.exe fc_putcset
	fc_putcset.exe
	hlacmp fc_putcset.data fc_putcset.txt

	hla -@@ -p:temp -obj:temp -x:fc_pute.exe fc_pute
	fc_pute.exe
	hlacmp fc_pute.data fc_pute.txt

	hla -@@ -p:temp -obj:temp -x:fc_putr.exe fc_putr
	fc_putr.exe
	hlacmp fc_putr.data fc_putr.txt


	hla -@@ -p:temp -obj:temp -x:vfc_getc.exe vfc_getc
	vfc_getc.exe
	hla -@@ -p:temp -obj:temp -x:vfc_agets.exe vfc_agets
	vfc_agets.exe
	hla -@@ -p:temp -obj:temp -x:vfc_getf.exe vfc_getf
	vfc_getf.exe
	hla -@@ -p:temp -obj:temp -x:vfc_gethex.exe vfc_gethex
	vfc_gethex.exe
	hla -@@ -p:temp -obj:temp -x:vfc_geti.exe vfc_geti
	vfc_geti.exe
	hla -@@ -p:temp -obj:temp -x:vfc_geti64.exe vfc_geti64
	vfc_geti64.exe
	hla -@@ -p:temp -obj:temp -x:vfc_geti128.exe vfc_geti128
	vfc_geti128.exe
	hla -@@ -p:temp -obj:temp -x:vfc_getu.exe vfc_getu
	vfc_getu.exe
	hla -@@ -p:temp -obj:temp -x:vfc_getu64.exe vfc_getu64
	vfc_getu64.exe
	hla -@@ -p:temp -obj:temp -x:vfc_getu128.exe vfc_getu128
	vfc_getu128.exe

	hla -@@ -p:temp -obj:temp -x:vfc_puthex.exe vfc_puthex
	vfc_puthex.exe
	hlacmp fc_puthex.data vfc_puthex.txt

	hla -@@ -p:temp -obj:temp -x:vfc_putu.exe vfc_putu
	vfc_putu.exe
	hlacmp fc_putu.data vfc_putu.txt

	hla -@@ -p:temp -obj:temp -x:vfc_puti.exe vfc_puti
	vfc_puti.exe
	hlacmp fc_puti.data vfc_puti.txt

	hla -@@ -p:temp -obj:temp -x:vfc_putbool.exe vfc_putbool
	vfc_putbool.exe
	hlacmp fc_putbool.data vfc_putbool.txt

	hla -@@ -p:temp -obj:temp -x:vfc_putcset.exe vfc_putcset
	vfc_putcset.exe
	hlacmp fc_putcset.data vfc_putcset.txt

	hla -@@ -p:temp -obj:temp -x:vfc_pute.exe vfc_pute
	vfc_pute.exe
	hlacmp fc_pute.data vfc_pute.txt

	hla -@@ -p:temp -obj:temp -x:vfc_putr.exe vfc_putr
	vfc_putr.exe
	hlacmp fc_putr.data vfc_putr.txt



	

thread:
	hla -@@ -thread -p:temp -obj:temp -x:fc_getc.exe fc_getc
	fc_getc.exe
	hla -@@ -thread -p:temp -obj:temp -x:fc_agets.exe fc_agets
	fc_agets.exe
	hla -@@ -thread -p:temp -obj:temp -x:fc_getf.exe fc_getf
	fc_getf.exe
	hla -@@ -thread -p:temp -obj:temp -x:fc_gethex.exe fc_gethex
	fc_gethex.exe
	hla -@@ -thread -p:temp -obj:temp -x:fc_geti.exe fc_geti
	fc_geti.exe
	hla -@@ -thread -p:temp -obj:temp -x:fc_geti64.exe fc_geti64
	fc_geti64.exe
	hla -@@ -thread -p:temp -obj:temp -x:fc_geti128.exe fc_geti128
	fc_geti128.exe
	hla -@@ -thread -p:temp -obj:temp -x:fc_getu.exe fc_getu
	fc_getu.exe
	hla -@@ -thread -p:temp -obj:temp -x:fc_getu64.exe fc_getu64
	fc_getu64.exe
	hla -@@ -thread -p:temp -obj:temp -x:fc_getu128.exe fc_getu128
	fc_getu128.exe

	hla -@@ -thread -p:temp -obj:temp -x:fc_puthex.exe fc_puthex
	fc_puthex.exe
	hlacmp fc_puthex.data fc_puthex.txt

	hla -@@ -thread -p:temp -obj:temp -x:fc_putu.exe fc_putu
	fc_putu.exe
	hlacmp fc_putu.data fc_putu.txt

	hla -@@ -thread -p:temp -obj:temp -x:fc_puti.exe fc_puti
	fc_puti.exe
	hlacmp fc_puti.data fc_puti.txt

	hla -@@ -thread -p:temp -obj:temp -x:fc_putbool.exe fc_putbool
	fc_putbool.exe
	hlacmp fc_putbool.data fc_putbool.txt

	hla -@@ -thread -p:temp -obj:temp -x:fc_putcset.exe fc_putcset
	fc_putcset.exe
	hlacmp fc_putcset.data fc_putcset.txt

	hla -@@ -thread -p:temp -obj:temp -x:fc_pute.exe fc_pute
	fc_pute.exe
	hlacmp fc_pute.data fc_pute.txt

	hla -@@ -thread -p:temp -obj:temp -x:fc_putr.exe fc_putr
	fc_putr.exe
	hlacmp fc_putr.data fc_putr.txt


	hla -@@ -thread -p:temp -obj:temp -x:vfc_getc.exe vfc_getc
	vfc_getc.exe
	hla -@@ -thread -p:temp -obj:temp -x:vfc_agets.exe vfc_agets
	vfc_agets.exe
	hla -@@ -thread -p:temp -obj:temp -x:vfc_getf.exe vfc_getf
	vfc_getf.exe
	hla -@@ -thread -p:temp -obj:temp -x:vfc_gethex.exe vfc_gethex
	vfc_gethex.exe
	hla -@@ -thread -p:temp -obj:temp -x:vfc_geti.exe vfc_geti
	vfc_geti.exe
	hla -@@ -thread -p:temp -obj:temp -x:vfc_geti64.exe vfc_geti64
	vfc_geti64.exe
	hla -@@ -thread -p:temp -obj:temp -x:vfc_geti128.exe vfc_geti128
	vfc_geti128.exe
	hla -@@ -thread -p:temp -obj:temp -x:vfc_getu.exe vfc_getu
	vfc_getu.exe
	hla -@@ -thread -p:temp -obj:temp -x:vfc_getu64.exe vfc_getu64
	vfc_getu64.exe
	hla -@@ -thread -p:temp -obj:temp -x:vfc_getu128.exe vfc_getu128
	vfc_getu128.exe

	hla -@@ -thread -p:temp -obj:temp -x:vfc_puthex.exe vfc_puthex
	vfc_puthex.exe
	hlacmp fc_puthex.data vfc_puthex.txt

	hla -@@ -thread -p:temp -obj:temp -x:vfc_putu.exe vfc_putu
	vfc_putu.exe
	hlacmp fc_putu.data vfc_putu.txt

	hla -@@ -thread -p:temp -obj:temp -x:vfc_puti.exe vfc_puti
	vfc_puti.exe
	hlacmp fc_puti.data vfc_puti.txt

	hla -@@ -thread -p:temp -obj:temp -x:vfc_putbool.exe vfc_putbool
	vfc_putbool.exe
	hlacmp fc_putbool.data vfc_putbool.txt

	hla -@@ -thread -p:temp -obj:temp -x:vfc_putcset.exe vfc_putcset
	vfc_putcset.exe
	hlacmp fc_putcset.data vfc_putcset.txt

	hla -@@ -thread -p:temp -obj:temp -x:vfc_pute.exe vfc_pute
	vfc_pute.exe
	hlacmp fc_pute.data vfc_pute.txt

	hla -@@ -thread -p:temp -obj:temp -x:vfc_putr.exe vfc_putr
	vfc_putr.exe
	hlacmp fc_putr.data vfc_putr.txt



	

clean:
	delete temp
	delete .inc
	delete .o
	delete .obj
	delete .link
	delete .exe
	delete .asm
	delete .txt
	delete .pdb
	delete .ilk
	