all:
	hla -@@ -p:temp -obj:temp -x:internal.exe internal
	internal.exe
	hla -@@ -p:temp -obj:temp -x:internal2.exe internal2
	internal2.exe
	hla -@@ -p:temp -obj:temp -x:internal3.exe internal3
	internal3.exe
	
	hla -@@ -p:temp -obj:temp -x:engtest.exe engtest
	engtest.exe
	hla -@@ -p:temp -obj:temp -x:romantest.exe romantest
	romantest.exe
	
	hla -@@ -p:temp -obj:temp -x:atof.exe atof
	atof.exe <atof.data
	hla -@@ -p:temp -obj:temp -x:convetobuf.exe convetobuf
	convetobuf.exe
	hla -@@ -p:temp -obj:temp -x:convetostr.exe convetostr
	convetostr.exe
	hla -@@ -p:temp -obj:temp -x:convr32tobuf.exe convr32tobuf
	convr32tobuf.exe
	hla -@@ -p:temp -obj:temp -x:convr64tobuf.exe convr64tobuf
	convr64tobuf.exe
	hla -@@ -p:temp -obj:temp -x:convr80tobuf.exe convr80tobuf
	convr80tobuf.exe
	hla -@@ -p:temp -obj:temp -x:convr32tostr.exe convr32tostr
	convr32tostr.exe
	hla -@@ -p:temp -obj:temp -x:convr64tostr.exe convr64tostr
	convr64tostr.exe
	hla -@@ -p:temp -obj:temp -x:convr80tostr.exe convr80tostr
	convr80tostr.exe



	hla -@@ -p:temp -obj:temp -x:conv_hsize.exe conv_hsize
	conv_hsize.exe
	hla -@@ -p:temp -obj:temp -x:convhsize.exe convhsize
	convhsize.exe
	hla -@@ -p:temp -obj:temp -x:convhex.exe convhex
	convhex.exe
	hla -@@ -p:temp -obj:temp -x:convhtobuf1.exe convhtobuf1
	convhtobuf1.exe
	hla -@@ -p:temp -obj:temp -x:convhtobuf2.exe convhtobuf2
	convhtobuf2.exe
	hla -@@ -p:temp -obj:temp -x:conv_htobuf1.exe conv_htobuf1
	conv_htobuf1.exe
	hla -@@ -p:temp -obj:temp -x:conv_htobuf2.exe conv_htobuf2
	conv_htobuf2.exe
	hla -@@ -p:temp -obj:temp -x:convhtostr.exe convhtostr
	convhtostr.exe
	hla -@@ -p:temp -obj:temp -x:conv_htostr.exe conv_htostr
	conv_htostr.exe
	
	hla -@@ -p:temp -obj:temp -x:convusize.exe convusize
	convusize.exe
	hla -@@ -p:temp -obj:temp -x:conv_usize.exe conv_usize
	conv_usize.exe
	hla -@@ -p:temp -obj:temp -x:convuns.exe convuns
	convuns.exe
	hla -@@ -p:temp -obj:temp -x:convutobuf.exe convutobuf
	convutobuf.exe
	hla -@@ -p:temp -obj:temp -x:conv_utobuf.exe conv_utobuf
	conv_utobuf.exe
	hla -@@ -p:temp -obj:temp -x:convutostr.exe convutostr
	convutostr.exe
	hla -@@ -p:temp -obj:temp -x:conv_utostr.exe conv_utostr
	conv_utostr.exe
	
	
	hla -@@ -p:temp -obj:temp -x:convisize.exe convisize
	convisize.exe
	hla -@@ -p:temp -obj:temp -x:conv_isize.exe conv_isize
	conv_isize.exe
	hla -@@ -p:temp -obj:temp -x:convint.exe convint
	convint.exe
	hla -@@ -p:temp -obj:temp -x:convitobuf.exe convitobuf
	convitobuf.exe
	hla -@@ -p:temp -obj:temp -x:conv_itobuf.exe conv_itobuf
	conv_itobuf.exe
	hla -@@ -p:temp -obj:temp -x:convitostr.exe convitostr
	convitostr.exe
	hla -@@ -p:temp -obj:temp -x:conv_itostr.exe conv_itostr
	conv_itostr.exe
	
	
	
	

thread:
	hla -@@ -thread -p:temp -obj:temp -x:internal.exe internal
	internal.exe
	hla -@@ -thread -p:temp -obj:temp -x:internal2.exe internal2
	internal2.exe
	hla -@@ -thread -p:temp -obj:temp -x:internal3.exe internal3
	internal3.exe
	
	hla -@@ -thread -p:temp -obj:temp -x:engtest.exe engtest
	engtest.exe
	hla -@@ -thread -p:temp -obj:temp -x:romantest.exe romantest
	romantest.exe
	
	hla -@@ -thread -p:temp -obj:temp -x:atof.exe atof
	atof.exe <atof.data
	hla -@@ -thread -p:temp -obj:temp -x:convetobuf.exe convetobuf
	convetobuf.exe
	hla -@@ -thread -p:temp -obj:temp -x:convetostr.exe convetostr
	convetostr.exe
	hla -@@ -thread -p:temp -obj:temp -x:convr32tobuf.exe convr32tobuf
	convr32tobuf.exe
	hla -@@ -thread -p:temp -obj:temp -x:convr64tobuf.exe convr64tobuf
	convr64tobuf.exe
	hla -@@ -thread -p:temp -obj:temp -x:convr80tobuf.exe convr80tobuf
	convr80tobuf.exe
	hla -@@ -thread -p:temp -obj:temp -x:convr32tostr.exe convr32tostr
	convr32tostr.exe
	hla -@@ -thread -p:temp -obj:temp -x:convr64tostr.exe convr64tostr
	convr64tostr.exe
	hla -@@ -thread -p:temp -obj:temp -x:convr80tostr.exe convr80tostr
	convr80tostr.exe



	hla -@@ -thread -p:temp -obj:temp -x:conv_hsize.exe conv_hsize
	conv_hsize.exe
	hla -@@ -thread -p:temp -obj:temp -x:convhsize.exe convhsize
	convhsize.exe
	hla -@@ -thread -p:temp -obj:temp -x:convhex.exe convhex
	convhex.exe
	hla -@@ -thread -p:temp -obj:temp -x:convhtobuf1.exe convhtobuf1
	convhtobuf1.exe
	hla -@@ -thread -p:temp -obj:temp -x:convhtobuf2.exe convhtobuf2
	convhtobuf2.exe
	hla -@@ -thread -p:temp -obj:temp -x:conv_htobuf1.exe conv_htobuf1
	conv_htobuf1.exe
	hla -@@ -thread -p:temp -obj:temp -x:conv_htobuf2.exe conv_htobuf2
	conv_htobuf2.exe
	hla -@@ -thread -p:temp -obj:temp -x:convhtostr.exe convhtostr
	convhtostr.exe
	hla -@@ -thread -p:temp -obj:temp -x:conv_htostr.exe conv_htostr
	conv_htostr.exe
	
	hla -@@ -thread -p:temp -obj:temp -x:convusize.exe convusize
	convusize.exe
	hla -@@ -thread -p:temp -obj:temp -x:conv_usize.exe conv_usize
	conv_usize.exe
	hla -@@ -thread -p:temp -obj:temp -x:convuns.exe convuns
	convuns.exe
	hla -@@ -thread -p:temp -obj:temp -x:convutobuf.exe convutobuf
	convutobuf.exe
	hla -@@ -thread -p:temp -obj:temp -x:conv_utobuf.exe conv_utobuf
	conv_utobuf.exe
	hla -@@ -thread -p:temp -obj:temp -x:convutostr.exe convutostr
	convutostr.exe
	hla -@@ -thread -p:temp -obj:temp -x:conv_utostr.exe conv_utostr
	conv_utostr.exe
	
	
	hla -@@ -thread -p:temp -obj:temp -x:convisize.exe convisize
	convisize.exe
	hla -@@ -thread -p:temp -obj:temp -x:conv_isize.exe conv_isize
	conv_isize.exe
	hla -@@ -thread -p:temp -obj:temp -x:convint.exe convint
	convint.exe
	hla -@@ -thread -p:temp -obj:temp -x:convitobuf.exe convitobuf
	convitobuf.exe
	hla -@@ -thread -p:temp -obj:temp -x:conv_itobuf.exe conv_itobuf
	conv_itobuf.exe
	hla -@@ -thread -p:temp -obj:temp -x:convitostr.exe convitostr
	convitostr.exe
	hla -@@ -thread -p:temp -obj:temp -x:conv_itostr.exe conv_itostr
	conv_itostr.exe
	
	
	
	

clean:
	delete temp
	delete .inc
	delete .o
	delete .obj
	delete .link
	delete .exe
	delete .asm
	delete .pdb
	delete .ilk
	