all:
	hla -@@ -p:temp -obj:temp -x:tZStrs.exe tZStrs
	tZStrs.exe

thread:
	hla -@@ -thread -p:temp -obj:temp -x:tZStrs.exe tZStrs
	tZStrs.exe

clean:
	delete temp
	delete .inc
	delete .o
	delete .obj
	delete .link
	delete .exe
	delete .asm
	delete .pdb
	delete .ilk
	