all:
	hla -@@ -p:temp -obj:temp -x:tFilesys.exe tFilesys.hla
	tFilesys.exe
	
thread:
	hla -@@ -thread -p:temp -obj:temp -x:tFilesys.exe tFilesys.hla
	tFilesys.exe
	

clean:
	delete temp
	delete .inc
	delete .o
	delete .obj
	delete .link
	delete .exe
	delete .asm
	delete .pdb
	delete .ilk
	