# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific aliases and functions

##
#ALIASES
##
alias logisim="java -jar /usr/csshare/bin/logisim-generic-2.7.1.jar"
