unittests: clean rclient.exe output
	hla -@@ -p:temp -obj:temp -x:tsock_getc.exe tsock_getc
	tsock_getc.exe
	hla -@@ -p:temp -obj:temp -x:tsock_agets.exe tsock_agets
	tsock_agets.exe
	hla -@@ -p:temp -obj:temp -x:tsock_getf.exe tsock_getf
	tsock_getf.exe
	hla -@@ -p:temp -obj:temp -x:tsock_gethex.exe tsock_gethex
	tsock_gethex.exe
	hla -@@ -p:temp -obj:temp -x:tsock_geti.exe tsock_geti
	tsock_geti.exe
	hla -@@ -p:temp -obj:temp -x:tsock_geti64.exe tsock_geti64
	tsock_geti64.exe
	hla -@@ -p:temp -obj:temp -x:tsock_geti128.exe tsock_geti128
	tsock_geti128.exe
	hla -@@ -p:temp -obj:temp -x:tsock_getu.exe tsock_getu
	tsock_getu.exe
	hla -@@ -p:temp -obj:temp -x:tsock_getu64.exe tsock_getu64
	tsock_getu64.exe
	hla -@@ -p:temp -obj:temp -x:tsock_getu128.exe tsock_getu128
	tsock_getu128.exe

	hla -@@ -p:temp -obj:temp -x:tvsock_getc.exe tvsock_getc
	tvsock_getc.exe
	hla -@@ -p:temp -obj:temp -x:tvsock_agets.exe tvsock_agets
	tvsock_agets.exe
	hla -@@ -p:temp -obj:temp -x:tvsock_getf.exe tvsock_getf
	tvsock_getf.exe
	hla -@@ -p:temp -obj:temp -x:tvsock_gethex.exe tvsock_gethex
	tsock_gethex.exe
	hla -@@ -p:temp -obj:temp -x:tvsock_geti.exe tvsock_geti
	tvsock_geti.exe
	hla -@@ -p:temp -obj:temp -x:tvsock_geti64.exe tvsock_geti64
	tsock_geti64.exe
	hla -@@ -p:temp -obj:temp -x:tvsock_geti128.exe tvsock_geti128
	tvsock_geti128.exe
	hla -@@ -p:temp -obj:temp -x:tvsock_getu.exe tvsock_getu
	tvsock_getu.exe
	hla -@@ -p:temp -obj:temp -x:tvsock_getu64.exe tvsock_getu64
	tvsock_getu64.exe
	hla -@@ -p:temp -obj:temp -x:tvsock_getu128.exe tvsock_getu128
	tvsock_getu128.exe

output: wclient.exe
	hla -@@ -p:temp -obj:temp -x:tsock_putbool.exe tsock_putbool
	tsock_putbool.exe
	hlacmp socket_putbool.data socket_putbool.txt

	hla -@@ -p:temp -obj:temp -x:tsock_putcset.exe tsock_putcset
	tsock_putcset.exe
	hlacmp socket_putcset.data socket_putcset.txt

	hla -@@ -p:temp -obj:temp -x:tsock_pute.exe tsock_pute
	tsock_pute.exe
	hlacmp socket_pute.data socket_pute.txt

	hla -@@ -p:temp -obj:temp -x:tsock_puthex.exe tsock_puthex
	tsock_puthex.exe
	hlacmp socket_puthex.data socket_puthex.txt

	hla -@@ -p:temp -obj:temp -x:tsock_puti.exe tsock_puti
	tsock_puti.exe
	hlacmp socket_puti.data socket_puti.txt

	hla -@@ -p:temp -obj:temp -x:tsock_putr.exe tsock_putr
	tsock_putr.exe
	hlacmp socket_putr.data socket_putr.txt

	hla -@@ -p:temp -obj:temp -x:tsock_putu.exe tsock_putu
	tsock_putu.exe
	hlacmp socket_putu.data socket_putu.txt


	hla -@@ -p:temp -obj:temp -x:tvsock_putbool.exe tvsock_putbool
	tvsock_putbool.exe
	hlacmp socket_putbool.data socket_putbool.txt

	hla -@@ -p:temp -obj:temp -x:tvsock_putcset.exe tvsock_putcset
	tvsock_putcset.exe
	hlacmp socket_putcset.data socket_putcset.txt

	hla -@@ -p:temp -obj:temp -x:tvsock_pute.exe tvsock_pute
	tvsock_pute.exe
	hlacmp socket_pute.data socket_pute.txt

	hla -@@ -p:temp -obj:temp -x:tvsock_puthex.exe tvsock_puthex
	tvsock_puthex.exe
	hlacmp socket_puthex.data socket_puthex.txt

	hla -@@ -p:temp -obj:temp -x:tvsock_puti.exe tvsock_puti
	tvsock_puti.exe
	hlacmp socket_puti.data socket_puti.txt

	hla -@@ -p:temp -obj:temp -x:tvsock_putr.exe tvsock_putr
	tvsock_putr.exe
	hlacmp socket_putr.data socket_putr.txt

	hla -@@ -p:temp -obj:temp -x:tvsock_putu.exe tvsock_putu
	tvsock_putu.exe
	hlacmp socket_putu.data socket_putu.txt


rclient.exe: rclient.hla	
	hla -@@ -p:temp -obj:temp -x:rclient.exe rclient

wclient.exe: wclient.hla	
	hla -@@ -p:temp -obj:temp -x:wclient.exe wclient






thread: clean rclientThread.exe outputThread
	hla -@@ -thread -p:temp -obj:temp -x:tsock_getc.exe tsock_getc
	tsock_getc.exe
	hla -@@ -thread -p:temp -obj:temp -x:tsock_agets.exe tsock_agets
	tsock_agets.exe
	hla -@@ -thread -p:temp -obj:temp -x:tsock_getf.exe tsock_getf
	tsock_getf.exe
	hla -@@ -thread -p:temp -obj:temp -x:tsock_gethex.exe tsock_gethex
	tsock_gethex.exe
	hla -@@ -thread -p:temp -obj:temp -x:tsock_geti.exe tsock_geti
	tsock_geti.exe
	hla -@@ -thread -p:temp -obj:temp -x:tsock_geti64.exe tsock_geti64
	tsock_geti64.exe
	hla -@@ -thread -p:temp -obj:temp -x:tsock_geti128.exe tsock_geti128
	tsock_geti128.exe
	hla -@@ -thread -p:temp -obj:temp -x:tsock_getu.exe tsock_getu
	tsock_getu.exe
	hla -@@ -thread -p:temp -obj:temp -x:tsock_getu64.exe tsock_getu64
	tsock_getu64.exe
	hla -@@ -thread -p:temp -obj:temp -x:tsock_getu128.exe tsock_getu128
	tsock_getu128.exe

	hla -@@ -thread -p:temp -obj:temp -x:tvsock_getc.exe tvsock_getc
	tvsock_getc.exe
	hla -@@ -thread -p:temp -obj:temp -x:tvsock_agets.exe tvsock_agets
	tvsock_agets.exe
	hla -@@ -thread -p:temp -obj:temp -x:tvsock_getf.exe tvsock_getf
	tvsock_getf.exe
	hla -@@ -thread -p:temp -obj:temp -x:tvsock_gethex.exe tvsock_gethex
	tsock_gethex.exe
	hla -@@ -thread -p:temp -obj:temp -x:tvsock_geti.exe tvsock_geti
	tvsock_geti.exe
	hla -@@ -thread -p:temp -obj:temp -x:tvsock_geti64.exe tvsock_geti64
	tsock_geti64.exe
	hla -@@ -thread -p:temp -obj:temp -x:tvsock_geti128.exe tvsock_geti128
	tvsock_geti128.exe
	hla -@@ -thread -p:temp -obj:temp -x:tvsock_getu.exe tvsock_getu
	tvsock_getu.exe
	hla -@@ -thread -p:temp -obj:temp -x:tvsock_getu64.exe tvsock_getu64
	tvsock_getu64.exe
	hla -@@ -thread -p:temp -obj:temp -x:tvsock_getu128.exe tvsock_getu128
	tvsock_getu128.exe

outputThread: wclientThread.exe
	hla -@@ -thread -p:temp -obj:temp -x:tsock_putbool.exe tsock_putbool
	tsock_putbool.exe
	hlacmp socket_putbool.data socket_putbool.txt

	hla -@@ -thread -p:temp -obj:temp -x:tsock_putcset.exe tsock_putcset
	tsock_putcset.exe
	hlacmp socket_putcset.data socket_putcset.txt

	hla -@@ -thread -p:temp -obj:temp -x:tsock_pute.exe tsock_pute
	tsock_pute.exe
	hlacmp socket_pute.data socket_pute.txt

	hla -@@ -thread -p:temp -obj:temp -x:tsock_puthex.exe tsock_puthex
	tsock_puthex.exe
	hlacmp socket_puthex.data socket_puthex.txt

	hla -@@ -thread -p:temp -obj:temp -x:tsock_puti.exe tsock_puti
	tsock_puti.exe
	hlacmp socket_puti.data socket_puti.txt

	hla -@@ -thread -p:temp -obj:temp -x:tsock_putr.exe tsock_putr
	tsock_putr.exe
	hlacmp socket_putr.data socket_putr.txt

	hla -@@ -thread -p:temp -obj:temp -x:tsock_putu.exe tsock_putu
	tsock_putu.exe
	hlacmp socket_putu.data socket_putu.txt


	hla -@@ -thread -p:temp -obj:temp -x:tvsock_putbool.exe tvsock_putbool
	tvsock_putbool.exe
	hlacmp socket_putbool.data socket_putbool.txt

	hla -@@ -thread -p:temp -obj:temp -x:tvsock_putcset.exe tvsock_putcset
	tvsock_putcset.exe
	hlacmp socket_putcset.data socket_putcset.txt

	hla -@@ -thread -p:temp -obj:temp -x:tvsock_pute.exe tvsock_pute
	tvsock_pute.exe
	hlacmp socket_pute.data socket_pute.txt

	hla -@@ -thread -p:temp -obj:temp -x:tvsock_puthex.exe tvsock_puthex
	tvsock_puthex.exe
	hlacmp socket_puthex.data socket_puthex.txt

	hla -@@ -thread -p:temp -obj:temp -x:tvsock_puti.exe tvsock_puti
	tvsock_puti.exe
	hlacmp socket_puti.data socket_puti.txt

	hla -@@ -thread -p:temp -obj:temp -x:tvsock_putr.exe tvsock_putr
	tvsock_putr.exe
	hlacmp socket_putr.data socket_putr.txt

	hla -@@ -thread -p:temp -obj:temp -x:tvsock_putu.exe tvsock_putu
	tvsock_putu.exe
	hlacmp socket_putu.data socket_putu.txt


rclientThread.exe: rclient.hla	
	hla -@@ -thread -p:temp -obj:temp -x:rclient.exe rclient

wclientThread.exe: wclient.hla	
	hla -@@ -thread -p:temp -obj:temp -x:wclient.exe wclient


clean:
	delete temp
	delete .inc
	delete .o
	delete .obj
	delete .link
	delete .exe
	delete .asm
	delete .txt
	delete .pdb
	delete .ilk
	delete .done
	