all: clearScrn clean odCmp hla/maketest
	cd hla; maketest freebsd; make


hla/maketest: maketest.hla
	hla -gas -source -p:tmp maketest.hla
	cp maketest hla


odCmp: odCmp.hla
	hla -gas -source -p:tmp odCmp
	cp odCmp hla

clearScrn:
	clear
	
clean: 
	rm -f -r tmp/*
	rm -f -r hla/*
	rm -f -r maketest
	rm -f -r odCmp
	


