all: date time


date:
	hla -@@ -p:temp -obj:temp -x:tDateAddDays.exe tDateAddDays
	tDateAddDays.exe
	hla -@@ -p:temp -obj:temp -x:tDateAddMonths.exe tDateAddMonths
	tDateAddMonths.exe
	hla -@@ -p:temp -obj:temp -x:tDateAddYears.exe tDateAddYears
	tDateAddYears.exe
	hla -@@ -p:temp -obj:temp -x:tDateDayNumber.exe tDateDayNumber
	tDateDayNumber.exe
	hla -@@ -p:temp -obj:temp -x:tDateDayOfWeek.exe tDateDayOfWeek
	tDateDayOfWeek.exe
	hla -@@ -p:temp -obj:temp -x:tDateDaysBetween.exe tDateDaysBetween
	tDateDaysBetween.exe
	hla -@@ -p:temp -obj:temp -x:tDateDaysLeft.exe tDateDaysLeft
	tDateDaysLeft.exe
	hla -@@ -p:temp -obj:temp -x:tDateFromJulian.exe tDateFromJulian
	tDateFromJulian.exe
	hla -@@ -p:temp -obj:temp -x:tDateIsLeapYear.exe tDateIsLeapYear
	tDateIsLeapYear.exe
	hla -@@ -p:temp -obj:temp -x:tDateIsValid.exe tDateIsValid
	tDateIsValid.exe
	hla -@@ -p:temp -obj:temp -x:tDateSubDays.exe tDateSubDays
	tDateSubDays.exe
	hla -@@ -p:temp -obj:temp -x:tDateSubMonths.exe tDateSubMonths
	tDateSubMonths.exe
	hla -@@ -p:temp -obj:temp -x:tDateSubYears.exe tDateSubYears
	tDateSubYears.exe
	hla -@@ -p:temp -obj:temp -x:tDateToJulian.exe tDateToJulian
	tDateToJulian.exe
	hla -@@ -p:temp -obj:temp -x:tDateToString.exe tDateToString
	tDateToString.exe >tDateToString.txt
	hlacmp tDateToString.txt dateToString.data
	hla -@@ -p:temp -obj:temp -x:tDateValidate.exe tDateValidate
	tDateValidate.exe
	
	hla -@@ -p:temp -obj:temp -x:tdc_addDays.exe tdc_addDays.hla
	tdc_addDays.exe
	hla -@@ -p:temp -obj:temp -x:tdc_addMonths.exe tdc_addMonths.hla
	tdc_addMonths.exe
	hla -@@ -p:temp -obj:temp -x:tdc_addYears.exe tdc_addYears.hla
	tdc_addYears.exe
	hla -@@ -p:temp -obj:temp -x:tdc_dayNumber.exe tdc_dayNumber.hla
	tdc_dayNumber.exe
	hla -@@ -p:temp -obj:temp -x:tdc_dayOfWeek.exe tdc_dayOfWeek.hla
	tdc_dayOfWeek.exe
	hla -@@ -p:temp -obj:temp -x:tdc_daysBetween.exe tdc_daysBetween.hla
	tdc_daysBetween.exe
	hla -@@ -p:temp -obj:temp -x:tdc_daysLeft.exe tdc_daysLeft.hla
	tdc_daysLeft.exe
	hla -@@ -p:temp -obj:temp -x:tdc_difference.exe tdc_difference.hla
	tdc_difference.exe
	hla -@@ -p:temp -obj:temp -x:tdc_fromJulian.exe tdc_fromJulian.hla
	tdc_fromJulian.exe
	hla -@@ -p:temp -obj:temp -x:tdc_isLeapYear.exe tdc_isLeapYear.hla
	tdc_isLeapYear.exe
	hla -@@ -p:temp -obj:temp -x:tdc_isValid.exe tdc_isValid.hla
	tdc_isValid.exe
	hla -@@ -p:temp -obj:temp -x:tdc_subDays.exe tdc_subDays.hla
	tdc_subDays.exe
	hla -@@ -p:temp -obj:temp -x:tdc_subMonths.exe tdc_subMonths.hla
	tdc_subMonths.exe
	hla -@@ -p:temp -obj:temp -x:tdc_subYears.exe tdc_subYears.hla
	tdc_subYears.exe
	hla -@@ -p:temp -obj:temp -x:tdc_toJulian.exe tdc_toJulian.hla
	tdc_toJulian.exe
	hla -@@ -p:temp -obj:temp -x:tdc_toString.exe tdc_toString.hla
	tdc_toString.exe
	hla -@@ -p:temp -obj:temp -x:tdc_validate.exe tdc_validate.hla
	tdc_validate.exe
	
time:
	hla -@@ -p:temp -obj:temp -x:tTimeAddHours.exe tTimeAddHours
	tTimeAddHours.exe
	hla -@@ -p:temp -obj:temp -x:tTimeAddMins.exe tTimeAddMins
	tTimeAddMins.exe
	hla -@@ -p:temp -obj:temp -x:tTimeAddSecs.exe tTimeAddSecs
	tTimeAddSecs.exe
	hla -@@ -p:temp -obj:temp -x:tTimeDurToSecs.exe tTimeDurToSecs
	tTimeDurToSecs.exe
	hla -@@ -p:temp -obj:temp -x:tTimeFromSecs.exe tTimeFromSecs
	tTimeFromSecs.exe
	hla -@@ -p:temp -obj:temp -x:tTimeFromUnix.exe tTimeFromUnix
	tTimeFromUnix.exe
	hla -@@ -p:temp -obj:temp -x:tTimeFromWinFileTime.exe tTimeFromWinFileTime
	tTimeFromWinFileTime.exe
	hla -@@ -p:temp -obj:temp -x:tTimeIsValid.exe tTimeIsValid
	tTimeIsValid.exe
	hla -@@ -p:temp -obj:temp -x:tTimeSecsBetweenTimes.exe tTimeSecsBetweenTimes
	tTimeSecsBetweenTimes.exe
	hla -@@ -p:temp -obj:temp -x:tTimeSecsToDur.exe tTimeSecsToDur
	tTimeSecsToDur.exe
	hla -@@ -p:temp -obj:temp -x:tTimeSubHours.exe tTimeSubHours
	tTimeSubHours.exe
	hla -@@ -p:temp -obj:temp -x:tTimeSubMins.exe tTimeSubMins
	tTimeSubMins.exe
	hla -@@ -p:temp -obj:temp -x:tTimeSubSecs.exe tTimeSubSecs
	tTimeSubSecs.exe
	hla -@@ -p:temp -obj:temp -x:tTimeToSecs.exe tTimeToSecs
	tTimeToSecs.exe
	hla -@@ -p:temp -obj:temp -x:tTimeToString.exe tTimeToString
	tTimeToString.exe
	hla -@@ -p:temp -obj:temp -x:tTimeToUnix.exe tTimeToUnix
	tTimeToUnix.exe
	hla -@@ -p:temp -obj:temp -x:tTimeToWinFileTime.exe tTimeToWinFileTime
	tTimeToWinFileTime.exe
	hla -@@ -p:temp -obj:temp -x:tTimeValidate.exe tTimeValidate
	tTimeValidate.exe
	hla -@@ -p:temp -obj:temp -x:tTimeCurTime.exe tTimeCurTime
	tTimeCurTime.exe
	
	hla -@@ -p:temp -obj:temp -x:ttc_AddHours.exe ttc_AddHours
	ttc_AddHours.exe
	hla -@@ -p:temp -obj:temp -x:ttc_AddMins.exe ttc_AddMins
	ttc_AddMins.exe
	hla -@@ -p:temp -obj:temp -x:ttc_AddSecs.exe ttc_AddSecs
	ttc_AddSecs.exe
	hla -@@ -p:temp -obj:temp -x:ttc_fromSecs.exe ttc_fromSecs
	ttc_fromSecs.exe
	hla -@@ -p:temp -obj:temp -x:ttc_IsValid.exe ttc_IsValid
	ttc_IsValid.exe
	hla -@@ -p:temp -obj:temp -x:ttc_SecsBetweenTimes.exe ttc_SecsBetweenTimes
	ttc_SecsBetweenTimes.exe
	hla -@@ -p:temp -obj:temp -x:ttc_SubHours.exe ttc_SubHours
	ttc_SubHours.exe
	hla -@@ -p:temp -obj:temp -x:ttc_SubMins.exe ttc_SubMins
	ttc_SubMins.exe
	hla -@@ -p:temp -obj:temp -x:ttc_SubSecs.exe ttc_SubSecs
	ttc_SubSecs.exe
	hla -@@ -p:temp -obj:temp -x:ttc_toSecs.exe ttc_toSecs
	ttc_toSecs.exe
	hla -@@ -p:temp -obj:temp -x:ttc_toString.exe ttc_toString
	ttc_toString.exe
	hla -@@ -p:temp -obj:temp -x:ttc_validate.exe ttc_validate
	ttc_validate.exe
	
	
	

thread: dateThread timeThread


dateThread:
	hla -@@ -thread -p:temp -obj:temp -x:tDateAddDays.exe tDateAddDays
	tDateAddDays.exe
	hla -@@ -thread -p:temp -obj:temp -x:tDateAddMonths.exe tDateAddMonths
	tDateAddMonths.exe
	hla -@@ -thread -p:temp -obj:temp -x:tDateAddYears.exe tDateAddYears
	tDateAddYears.exe
	hla -@@ -thread -p:temp -obj:temp -x:tDateDayNumber.exe tDateDayNumber
	tDateDayNumber.exe
	hla -@@ -thread -p:temp -obj:temp -x:tDateDayOfWeek.exe tDateDayOfWeek
	tDateDayOfWeek.exe
	hla -@@ -thread -p:temp -obj:temp -x:tDateDaysBetween.exe tDateDaysBetween
	tDateDaysBetween.exe
	hla -@@ -thread -p:temp -obj:temp -x:tDateDaysLeft.exe tDateDaysLeft
	tDateDaysLeft.exe
	hla -@@ -thread -p:temp -obj:temp -x:tDateFromJulian.exe tDateFromJulian
	tDateFromJulian.exe
	hla -@@ -thread -p:temp -obj:temp -x:tDateIsLeapYear.exe tDateIsLeapYear
	tDateIsLeapYear.exe
	hla -@@ -thread -p:temp -obj:temp -x:tDateIsValid.exe tDateIsValid
	tDateIsValid.exe
	hla -@@ -thread -p:temp -obj:temp -x:tDateSubDays.exe tDateSubDays
	tDateSubDays.exe
	hla -@@ -thread -p:temp -obj:temp -x:tDateSubMonths.exe tDateSubMonths
	tDateSubMonths.exe
	hla -@@ -thread -p:temp -obj:temp -x:tDateSubYears.exe tDateSubYears
	tDateSubYears.exe
	hla -@@ -thread -p:temp -obj:temp -x:tDateToJulian.exe tDateToJulian
	tDateToJulian.exe
	hla -@@ -thread -p:temp -obj:temp -x:tDateToString.exe tDateToString
	tDateToString.exe >tDateToString.txt
	hlacmp tDateToString.txt dateToString.data
	hla -@@ -thread -p:temp -obj:temp -x:tDateValidate.exe tDateValidate
	tDateValidate.exe
	
	hla -@@ -thread -p:temp -obj:temp -x:tdc_addDays.exe tdc_addDays.hla
	tdc_addDays.exe
	hla -@@ -thread -p:temp -obj:temp -x:tdc_addMonths.exe tdc_addMonths.hla
	tdc_addMonths.exe
	hla -@@ -thread -p:temp -obj:temp -x:tdc_addYears.exe tdc_addYears.hla
	tdc_addYears.exe
	hla -@@ -thread -p:temp -obj:temp -x:tdc_dayNumber.exe tdc_dayNumber.hla
	tdc_dayNumber.exe
	hla -@@ -thread -p:temp -obj:temp -x:tdc_dayOfWeek.exe tdc_dayOfWeek.hla
	tdc_dayOfWeek.exe
	hla -@@ -thread -p:temp -obj:temp -x:tdc_daysBetween.exe tdc_daysBetween.hla
	tdc_daysBetween.exe
	hla -@@ -thread -p:temp -obj:temp -x:tdc_daysLeft.exe tdc_daysLeft.hla
	tdc_daysLeft.exe
	hla -@@ -thread -p:temp -obj:temp -x:tdc_difference.exe tdc_difference.hla
	tdc_difference.exe
	hla -@@ -thread -p:temp -obj:temp -x:tdc_fromJulian.exe tdc_fromJulian.hla
	tdc_fromJulian.exe
	hla -@@ -thread -p:temp -obj:temp -x:tdc_isLeapYear.exe tdc_isLeapYear.hla
	tdc_isLeapYear.exe
	hla -@@ -thread -p:temp -obj:temp -x:tdc_isValid.exe tdc_isValid.hla
	tdc_isValid.exe
	hla -@@ -thread -p:temp -obj:temp -x:tdc_subDays.exe tdc_subDays.hla
	tdc_subDays.exe
	hla -@@ -thread -p:temp -obj:temp -x:tdc_subMonths.exe tdc_subMonths.hla
	tdc_subMonths.exe
	hla -@@ -thread -p:temp -obj:temp -x:tdc_subYears.exe tdc_subYears.hla
	tdc_subYears.exe
	hla -@@ -thread -p:temp -obj:temp -x:tdc_toJulian.exe tdc_toJulian.hla
	tdc_toJulian.exe
	hla -@@ -thread -p:temp -obj:temp -x:tdc_toString.exe tdc_toString.hla
	tdc_toString.exe
	hla -@@ -thread -p:temp -obj:temp -x:tdc_validate.exe tdc_validate.hla
	tdc_validate.exe
	
timeThread:
	hla -@@ -thread -p:temp -obj:temp -x:tTimeAddHours.exe tTimeAddHours
	tTimeAddHours.exe
	hla -@@ -thread -p:temp -obj:temp -x:tTimeAddMins.exe tTimeAddMins
	tTimeAddMins.exe
	hla -@@ -thread -p:temp -obj:temp -x:tTimeAddSecs.exe tTimeAddSecs
	tTimeAddSecs.exe
	hla -@@ -thread -p:temp -obj:temp -x:tTimeDurToSecs.exe tTimeDurToSecs
	tTimeDurToSecs.exe
	hla -@@ -thread -p:temp -obj:temp -x:tTimeFromSecs.exe tTimeFromSecs
	tTimeFromSecs.exe
	hla -@@ -thread -p:temp -obj:temp -x:tTimeFromUnix.exe tTimeFromUnix
	tTimeFromUnix.exe
	hla -@@ -thread -p:temp -obj:temp -x:tTimeFromWinFileTime.exe tTimeFromWinFileTime
	tTimeFromWinFileTime.exe
	hla -@@ -thread -p:temp -obj:temp -x:tTimeIsValid.exe tTimeIsValid
	tTimeIsValid.exe
	hla -@@ -thread -p:temp -obj:temp -x:tTimeSecsBetweenTimes.exe tTimeSecsBetweenTimes
	tTimeSecsBetweenTimes.exe
	hla -@@ -thread -p:temp -obj:temp -x:tTimeSecsToDur.exe tTimeSecsToDur
	tTimeSecsToDur.exe
	hla -@@ -thread -p:temp -obj:temp -x:tTimeSubHours.exe tTimeSubHours
	tTimeSubHours.exe
	hla -@@ -thread -p:temp -obj:temp -x:tTimeSubMins.exe tTimeSubMins
	tTimeSubMins.exe
	hla -@@ -thread -p:temp -obj:temp -x:tTimeSubSecs.exe tTimeSubSecs
	tTimeSubSecs.exe
	hla -@@ -thread -p:temp -obj:temp -x:tTimeToSecs.exe tTimeToSecs
	tTimeToSecs.exe
	hla -@@ -thread -p:temp -obj:temp -x:tTimeToString.exe tTimeToString
	tTimeToString.exe
	hla -@@ -thread -p:temp -obj:temp -x:tTimeToUnix.exe tTimeToUnix
	tTimeToUnix.exe
	hla -@@ -thread -p:temp -obj:temp -x:tTimeToWinFileTime.exe tTimeToWinFileTime
	tTimeToWinFileTime.exe
	hla -@@ -thread -p:temp -obj:temp -x:tTimeValidate.exe tTimeValidate
	tTimeValidate.exe
	hla -@@ -thread -p:temp -obj:temp -x:tTimeCurTime.exe tTimeCurTime
	tTimeCurTime.exe
	
	hla -@@ -thread -p:temp -obj:temp -x:ttc_AddHours.exe ttc_AddHours
	ttc_AddHours.exe
	hla -@@ -thread -p:temp -obj:temp -x:ttc_AddMins.exe ttc_AddMins
	ttc_AddMins.exe
	hla -@@ -thread -p:temp -obj:temp -x:ttc_AddSecs.exe ttc_AddSecs
	ttc_AddSecs.exe
	hla -@@ -thread -p:temp -obj:temp -x:ttc_fromSecs.exe ttc_fromSecs
	ttc_fromSecs.exe
	hla -@@ -thread -p:temp -obj:temp -x:ttc_IsValid.exe ttc_IsValid
	ttc_IsValid.exe
	hla -@@ -thread -p:temp -obj:temp -x:ttc_SecsBetweenTimes.exe ttc_SecsBetweenTimes
	ttc_SecsBetweenTimes.exe
	hla -@@ -thread -p:temp -obj:temp -x:ttc_SubHours.exe ttc_SubHours
	ttc_SubHours.exe
	hla -@@ -thread -p:temp -obj:temp -x:ttc_SubMins.exe ttc_SubMins
	ttc_SubMins.exe
	hla -@@ -thread -p:temp -obj:temp -x:ttc_SubSecs.exe ttc_SubSecs
	ttc_SubSecs.exe
	hla -@@ -thread -p:temp -obj:temp -x:ttc_toSecs.exe ttc_toSecs
	ttc_toSecs.exe
	hla -@@ -thread -p:temp -obj:temp -x:ttc_toString.exe ttc_toString
	ttc_toString.exe
	hla -@@ -thread -p:temp -obj:temp -x:ttc_validate.exe ttc_validate
	ttc_validate.exe
	
	
	

clean:
	delete temp
	delete .inc
	delete .o
	delete .obj
	delete .link
	delete .exe
	delete .asm
	delete .txt
	delete .ilk
	delete .pdb
	