all:
	echo TODO: Write WINDOWS unit tests

thread:
	echo TODO: Write WINDOWS unit tests

clean:
	delete temp
	delete .inc
	delete .o
	delete .obj
	delete .link
	delete .exe
	delete .asm
	delete .pdb
	delete .ilk
	