unittests:
	hla -@@ -p:temp -obj:temp -x:getc.exe getc
	getc.exe <getc.data

	hla -@@ -p:temp -obj:temp -x:peekc.exe peekc
	peekc.exe <peekc.data

	hla -@@ -p:temp -obj:temp -x:agets.exe agets
	agets.exe <agets.data

	hla -@@ -p:temp -obj:temp -x:eoln.exe eoln
	eoln.exe <eoln.data

	hla -@@ -p:temp -obj:temp -x:readln.exe readln
	readln.exe <readln.data

	hla -@@ -p:temp -obj:temp -x:getf.exe getf
	getf.exe <getf.data

	hla -@@ -p:temp -obj:temp -x:gethex.exe gethex
	gethex.exe <gethex.data

	hla -@@ -p:temp -obj:temp -x:geti.exe geti
	geti.exe <geti.data
	hla -@@ -p:temp -obj:temp -x:geti64.exe geti64
	geti64.exe <geti64.data
	hla -@@ -p:temp -obj:temp -x:geti128.exe geti128
	geti128.exe	<geti128.data

	hla -@@ -p:temp -obj:temp -x:getu.exe getu
	getu.exe <getu.data
	hla -@@ -p:temp -obj:temp -x:getu64.exe getu64
	getu64.exe	<getu64.data
	hla -@@ -p:temp -obj:temp -x:getu128.exe getu128
	getu128.exe	<getu128.data


thread:
	hla -@@ -thread -p:temp -obj:temp -x:getc.exe getc
	getc.exe <getc.data

	hla -@@ -thread -p:temp -obj:temp -x:peekc.exe peekc
	peekc.exe <peekc.data

	hla -@@ -thread -p:temp -obj:temp -x:agets.exe agets
	agets.exe <agets.data

	hla -@@ -thread -p:temp -obj:temp -x:eoln.exe eoln
	eoln.exe <eoln.data

	hla -@@ -thread -p:temp -obj:temp -x:readln.exe readln
	readln.exe <readln.data

	hla -@@ -thread -p:temp -obj:temp -x:getf.exe getf
	getf.exe <getf.data

	hla -@@ -thread -p:temp -obj:temp -x:gethex.exe gethex
	gethex.exe <gethex.data

	hla -@@ -thread -p:temp -obj:temp -x:geti.exe geti
	geti.exe <geti.data
	hla -@@ -thread -p:temp -obj:temp -x:geti64.exe geti64
	geti64.exe <geti64.data
	hla -@@ -thread -p:temp -obj:temp -x:geti128.exe geti128
	geti128.exe	<geti128.data

	hla -@@ -thread -p:temp -obj:temp -x:getu.exe getu
	getu.exe <getu.data
	hla -@@ -thread -p:temp -obj:temp -x:getu64.exe getu64
	getu64.exe	<getu64.data
	hla -@@ -thread -p:temp -obj:temp -x:getu128.exe getu128
	getu128.exe	<getu128.data


clean:
	delete temp
	delete .inc
	delete .o
	delete .obj
	delete .link
	delete .exe
	delete .asm
	delete .txt
	delete .pdb
	delete .ilk
	