all:
	hla -@@ -p:temp -obj:temp -x:tIsAlpha.exe tIsAlpha
	tIsAlpha.exe
	hla -@@ -p:temp -obj:temp -x:tIsAlphanum.exe tIsAlphanum
	tIsAlphanum.exe
	hla -@@ -p:temp -obj:temp -x:tIsAscii.exe tIsAscii
	tIsAscii.exe
	hla -@@ -p:temp -obj:temp -x:tisCtrl.exe tisCtrl
	tisCtrl.exe
	hla -@@ -p:temp -obj:temp -x:tIsDigit.exe tIsDigit
	tIsDigit.exe
	hla -@@ -p:temp -obj:temp -x:tIsGraphic.exe tIsGraphic
	tIsGraphic.exe
	hla -@@ -p:temp -obj:temp -x:tIsLower.exe tIsLower
	tIsLower.exe
	hla -@@ -p:temp -obj:temp -x:tIsSpace.exe tIsSpace
	tIsSpace.exe
	hla -@@ -p:temp -obj:temp -x:tIsUpper.exe tIsUpper
	tIsUpper.exe
	hla -@@ -p:temp -obj:temp -x:tIsXDigit.exe tIsXDigit
	tIsXDigit.exe
	hla -@@ -p:temp -obj:temp -x:tToLower.exe tToLower
	tToLower.exe
	hla -@@ -p:temp -obj:temp -x:tToUpper.exe tToUpper
	tToUpper.exe
	
thread:
	hla -@@ -p:temp -obj:temp -x:tIsAlpha.exe -thread tIsAlpha
	tIsAlpha.exe
	hla -@@ -p:temp -obj:temp -x:tIsAlphanum.exe -thread tIsAlphanum
	tIsAlphanum.exe
	hla -@@ -p:temp -obj:temp -x:tIsAscii.exe -thread tIsAscii
	tIsAscii.exe
	hla -@@ -p:temp -obj:temp -x:tisCtrl.exe -thread tisCtrl
	tisCtrl.exe
	hla -@@ -p:temp -obj:temp -x:tIsDigit.exe -thread tIsDigit
	tIsDigit.exe
	hla -@@ -p:temp -obj:temp -x:tIsGraphic.exe -thread tIsGraphic
	tIsGraphic.exe
	hla -@@ -p:temp -obj:temp -x:tIsLower.exe -thread tIsLower
	tIsLower.exe
	hla -@@ -p:temp -obj:temp -x:tIsSpace.exe -thread tIsSpace
	tIsSpace.exe
	hla -@@ -p:temp -obj:temp -x:tIsUpper.exe -thread tIsUpper
	tIsUpper.exe
	hla -@@ -p:temp -obj:temp -x:tIsXDigit.exe -thread tIsXDigit
	tIsXDigit.exe
	hla -@@ -p:temp -obj:temp -x:tToLower.exe -thread tToLower
	tToLower.exe
	hla -@@ -p:temp -obj:temp -x:tToUpper.exe -thread tToUpper
	tToUpper.exe
	
clean:
	delete temp
	delete .inc
	delete .o
	delete .obj
	delete .link
	delete .exe
	delete .asm
	delete .pdb
	delete .ilk
	