all:
	hla -@@ -p:temp -obj:temp -x:tTables.exe tTables
	tTables.exe

thread:
	hla -@@ -thread -p:temp -obj:temp -x:tTables.exe tTables
	tTables.exe

clean:
	delete temp
	delete .inc
	delete .o
	delete .obj
	delete .link
	delete .exe
	delete .asm
	delete .pdb
	delete .ilk
	