unittests:
	hla -@@ -p:temp -x:tPathStr.exe tPathStr
	tPathStr.exe


thread:
	hla -@@ -thread -p:temp -x:tPathStr.exe tPathStr
	tPathStr.exe


	

clean:
	delete temp
	delete .inc
	delete .o
	delete .obj
	delete .link
	delete .exe
	delete .asm
	delete .txt
	delete .pdb
	delete .ilk
	