all:
	hla -@@ -p:temp -obj:temp -x:tTrig.exe tTrig
	tTrig.exe
	hla -@@ -p:temp -obj:temp -x:tLogarithms.exe tLogarithms
	tLogarithms.exe
	hla -@@ -p:temp -obj:temp -x:tArithmetic.exe tArithmetic
	tArithmetic.exe
	hla -@@ -p:temp -obj:temp -x:tDivq.exe tDivq
	tDivq.exe
	hla -@@ -p:temp -obj:temp -x:tDivl.exe tDivl
	tDivl.exe
	hla -@@ -p:temp -obj:temp -x:tModq.exe tModq
	tModq.exe
	hla -@@ -p:temp -obj:temp -x:tModl.exe tModl
	tModl.exe
	hla -@@ -p:temp -obj:temp -x:tLogical.exe tLogical
	tLogical.exe

thread:	 
	hla -@@ -thread -p:temp -obj:temp -x:tTrig.exe tTrig
	tTrig.exe
	hla -@@ -thread -p:temp -obj:temp -x:tLogarithms.exe tLogarithms
	tLogarithms.exe
	hla -@@ -thread -p:temp -obj:temp -x:tArithmetic.exe tArithmetic
	tArithmetic.exe
	hla -@@ -thread -p:temp -obj:temp -x:tDivq.exe tDivq
	tDivq.exe
	hla -@@ -thread -p:temp -obj:temp -x:tDivl.exe tDivl
	tDivl.exe
	hla -@@ -thread -p:temp -obj:temp -x:tModq.exe tModq
	tModq.exe
	hla -@@ -thread -p:temp -obj:temp -x:tModl.exe tModl
	tModl.exe
	hla -@@ -thread -p:temp -obj:temp -x:tLogical.exe tLogical
	tLogical.exe

clean:
	delete temp
	delete .inc
	delete .o
	delete .obj
	delete .link
	delete .exe
	delete .asm
	delete .pdb
	delete .ilk
	