unittests:
	hla -@@ -p:temp -obj:temp -x:puthex.exe puthex
	puthex.exe >puthex.txt
	hlacmp puthex.data puthex.txt

	hla -@@ -p:temp -obj:temp -x:putu.exe putu
	putu.exe >putu.txt
	hlacmp putu.data putu.txt

	hla -@@ -p:temp -obj:temp -x:puti.exe puti
	puti.exe >puti.txt
	hlacmp puti.data puti.txt

	hla -@@ -p:temp -obj:temp -x:putbool.exe putbool
	putbool.exe >putbool.txt
	hlacmp putbool.data putbool.txt

	hla -@@ -p:temp -obj:temp -x:putcset.exe putcset
	putcset.exe >putcset.txt
	hlacmp putcset.data putcset.txt

	hla -@@ -p:temp -obj:temp -x:pute.exe pute
	pute.exe >pute.txt
	hlacmp pute.data pute.txt

	hla -@@ -p:temp -obj:temp -x:putr.exe putr
	putr.exe >putr.txt
	hlacmp putr.data putr.txt


	

thread:
	hla -@@ -thread -p:temp -obj:temp -x:puthex.exe puthex
	puthex.exe >puthex.txt
	hlacmp puthex.data puthex.txt

	hla -@@ -thread -p:temp -obj:temp -x:putu.exe putu
	putu.exe >putu.txt
	hlacmp putu.data putu.txt

	hla -@@ -thread -p:temp -obj:temp -x:puti.exe puti
	puti.exe >puti.txt
	hlacmp puti.data puti.txt

	hla -@@ -thread -p:temp -obj:temp -x:putbool.exe putbool
	putbool.exe >putbool.txt
	hlacmp putbool.data putbool.txt

	hla -@@ -thread -p:temp -obj:temp -x:putcset.exe putcset
	putcset.exe >putcset.txt
	hlacmp putcset.data putcset.txt

	hla -@@ -thread -p:temp -obj:temp -x:pute.exe pute
	pute.exe >pute.txt
	hlacmp pute.data pute.txt

	hla -@@ -thread -p:temp -obj:temp -x:putr.exe putr
	putr.exe >putr.txt
	hlacmp putr.data putr.txt


	

clean:
	delete temp
	delete .inc
	delete .o
	delete .obj
	delete .link
	delete .exe
	delete .asm
	delete .txt
	delete .pdb
	delete .ilk
	