all:
	hla -@@ -p:temp -obj:temp -x:tchartocset.exe tchartocset.hla
	tchartocset.exe
	hla -@@ -p:temp -obj:temp -x:tcomplement.exe tcomplement.hla
	tcomplement.exe
	hla -@@ -p:temp -obj:temp -x:tcscpy.exe tcscpy.hla
	tcscpy.exe
	hla -@@ -p:temp -obj:temp -x:tcseqne.exe tcseqne.hla
	tcseqne.exe
	hla -@@ -p:temp -obj:temp -x:tdifference.exe tdifference.hla
	tdifference.exe
	hla -@@ -p:temp -obj:temp -x:tempty.exe tempty.hla
	tempty.exe
	hla -@@ -p:temp -obj:temp -x:textract.exe textract.hla
	textract.exe
	hla -@@ -p:temp -obj:temp -x:tintersection.exe tintersection.hla
	tintersection.exe
	hla -@@ -p:temp -obj:temp -x:tmember.exe tmember.hla
	tmember.exe
	hla -@@ -p:temp -obj:temp -x:tsubset.exe tsubset.hla
	tsubset.exe
	hla -@@ -p:temp -obj:temp -x:tsuperset.exe tsuperset.hla
	tsuperset.exe
	hla -@@ -p:temp -obj:temp -x:trangechar.exe trangechar.hla
	trangechar.exe
	hla -@@ -p:temp -obj:temp -x:tremovechar.exe tremovechar.hla
	tremovechar.exe
	hla -@@ -p:temp -obj:temp -x:tremovestr.exe tremovestr.hla
	tremovestr.exe
	hla -@@ -p:temp -obj:temp -x:tstrtocset.exe tstrtocset.hla
	tstrtocset.exe
	hla -@@ -p:temp -obj:temp -x:tunion.exe tunion.hla
	tunion.exe
	hla -@@ -p:temp -obj:temp -x:tunionchar.exe tunionchar.hla
	tunionchar.exe

thread:
	hla -@@ -thread -p:temp -obj:temp -x:tchartocset.exe tchartocset.hla
	tchartocset.exe
	hla -@@ -thread -p:temp -obj:temp -x:tcomplement.exe tcomplement.hla
	tcomplement.exe
	hla -@@ -thread -p:temp -obj:temp -x:tcscpy.exe tcscpy.hla
	tcscpy.exe
	hla -@@ -thread -p:temp -obj:temp -x:tcseqne.exe tcseqne.hla
	tcseqne.exe
	hla -@@ -thread -p:temp -obj:temp -x:tdifference.exe tdifference.hla
	tdifference.exe
	hla -@@ -thread -p:temp -obj:temp -x:tempty.exe tempty.hla
	tempty.exe
	hla -@@ -thread -p:temp -obj:temp -x:textract.exe textract.hla
	textract.exe
	hla -@@ -thread -p:temp -obj:temp -x:tintersection.exe tintersection.hla
	tintersection.exe
	hla -@@ -thread -p:temp -obj:temp -x:tmember.exe tmember.hla
	tmember.exe
	hla -@@ -thread -p:temp -obj:temp -x:tsubset.exe tsubset.hla
	tsubset.exe
	hla -@@ -thread -p:temp -obj:temp -x:tsuperset.exe tsuperset.hla
	tsuperset.exe
	hla -@@ -thread -p:temp -obj:temp -x:trangechar.exe trangechar.hla
	trangechar.exe
	hla -@@ -thread -p:temp -obj:temp -x:tremovechar.exe tremovechar.hla
	tremovechar.exe
	hla -@@ -thread -p:temp -obj:temp -x:tremovestr.exe tremovestr.hla
	tremovestr.exe
	hla -@@ -thread -p:temp -obj:temp -x:tstrtocset.exe tstrtocset.hla
	tstrtocset.exe
	hla -@@ -thread -p:temp -obj:temp -x:tunion.exe tunion.hla
	tunion.exe
	hla -@@ -thread -p:temp -obj:temp -x:tunionchar.exe tunionchar.hla
	tunionchar.exe

clean:
	delete temp
	delete .inc
	delete .o
	delete .obj
	delete .link
	delete .exe
	delete .asm
	delete .pdb
	delete .ilk
	