unittests:
	hla -@@ -p:temp -obj:temp -x:bIndex.exe bIndex
	bIndex.exe
	hla -@@ -p:temp -obj:temp -x:bSub.exe bSub
	bSub.exe
	hla -@@ -p:temp -obj:temp -x:bCat.exe bCat
	bCat.exe
	hla -@@ -p:temp -obj:temp -x:bCopy.exe bCopy
	bCopy.exe
	hla -@@ -p:temp -obj:temp -x:bBinaryIO.exe bBinaryIO
	bBinaryIO.exe
	hla -@@ -p:temp -obj:temp -x:bAccessor.exe bAccessor
	bAccessor.exe
	hla -@@ -p:temp -obj:temp -x:bAlloc.exe bAlloc
	bAlloc.exe
	hla -@@ -p:temp -obj:temp -x:bgetc.exe bgetc
	bgetc.exe
	hla -@@ -p:temp -obj:temp -x:bagets.exe bagets
	bagets.exe
	hla -@@ -p:temp -obj:temp -x:bgetf.exe bgetf
	bgetf.exe
	hla -@@ -p:temp -obj:temp -x:bgethex.exe bgethex
	bgethex.exe
	hla -@@ -p:temp -obj:temp -x:bgeti.exe bgeti
	bgeti.exe
	hla -@@ -p:temp -obj:temp -x:bgeti64.exe bgeti64
	bgeti64.exe
	hla -@@ -p:temp -obj:temp -x:bgeti128.exe bgeti128
	bgeti128.exe
	hla -@@ -p:temp -obj:temp -x:bgetu.exe bgetu
	bgetu.exe
	hla -@@ -p:temp -obj:temp -x:bgetu64.exe bgetu64
	bgetu64.exe
	hla -@@ -p:temp -obj:temp -x:bgetu128.exe bgetu128
	bgetu128.exe

	hla -@@ -p:temp -obj:temp -x:bputhex.exe bputhex
	bputhex.exe
	hlacmp bputhex.data bputhex.txt

	hla -@@ -p:temp -obj:temp -x:bputu.exe bputu
	bputu.exe
	hlacmp bputu.data bputu.txt

	hla -@@ -p:temp -obj:temp -x:bputi.exe bputi
	bputi.exe
	hlacmp bputi.data bputi.txt

	hla -@@ -p:temp -obj:temp -x:bputbool.exe bputbool
	bputbool.exe
	hlacmp bputbool.data bputbool.txt

	hla -@@ -p:temp -obj:temp -x:bputcset.exe bputcset
	bputcset.exe
	hlacmp bputcset.data bputcset.txt

	hla -@@ -p:temp -obj:temp -x:bpute.exe bpute
	bpute.exe
	hlacmp bpute.data bpute.txt

	hla -@@ -p:temp -obj:temp -x:bputr.exe bputr
	bputr.exe
	hlacmp bputr.data bputr.txt

	hla -@@ -p:temp -obj:temp -x:bFile.exe bFile
	bFile.exe




	

thread:
	hla -@@ -thread -p:temp -obj:temp -x:bIndex.exe bIndex
	bIndex.exe
	hla -@@ -thread -p:temp -obj:temp -x:bSub.exe bSub
	bSub.exe
	hla -@@ -thread -p:temp -obj:temp -x:bCat.exe bCat
	bCat.exe
	hla -@@ -thread -p:temp -obj:temp -x:bCopy.exe bCopy
	bCopy.exe
	hla -@@ -thread -p:temp -obj:temp -x:bBinaryIO.exe bBinaryIO
	bBinaryIO.exe
	hla -@@ -thread -p:temp -obj:temp -x:bAccessor.exe bAccessor
	bAccessor.exe
	hla -@@ -thread -p:temp -obj:temp -x:bAlloc.exe bAlloc
	bAlloc.exe
	hla -@@ -thread -p:temp -obj:temp -x:bgetc.exe bgetc
	bgetc.exe
	hla -@@ -thread -p:temp -obj:temp -x:bagets.exe bagets
	bagets.exe
	hla -@@ -thread -p:temp -obj:temp -x:bgetf.exe bgetf
	bgetf.exe
	hla -@@ -thread -p:temp -obj:temp -x:bgethex.exe bgethex
	bgethex.exe
	hla -@@ -thread -p:temp -obj:temp -x:bgeti.exe bgeti
	bgeti.exe
	hla -@@ -thread -p:temp -obj:temp -x:bgeti64.exe bgeti64
	bgeti64.exe
	hla -@@ -thread -p:temp -obj:temp -x:bgeti128.exe bgeti128
	bgeti128.exe
	hla -@@ -thread -p:temp -obj:temp -x:bgetu.exe bgetu
	bgetu.exe
	hla -@@ -thread -p:temp -obj:temp -x:bgetu64.exe bgetu64
	bgetu64.exe
	hla -@@ -thread -p:temp -obj:temp -x:bgetu128.exe bgetu128
	bgetu128.exe

	hla -@@ -thread -p:temp -obj:temp -x:bputhex.exe bputhex
	bputhex.exe
	hlacmp bputhex.data bputhex.txt

	hla -@@ -thread -p:temp -obj:temp -x:bputu.exe bputu
	bputu.exe
	hlacmp bputu.data bputu.txt

	hla -@@ -thread -p:temp -obj:temp -x:bputi.exe bputi
	bputi.exe
	hlacmp bputi.data bputi.txt

	hla -@@ -thread -p:temp -obj:temp -x:bputbool.exe bputbool
	bputbool.exe
	hlacmp bputbool.data bputbool.txt

	hla -@@ -thread -p:temp -obj:temp -x:bputcset.exe bputcset
	bputcset.exe
	hlacmp bputcset.data bputcset.txt

	hla -@@ -thread -p:temp -obj:temp -x:bpute.exe bpute
	bpute.exe
	hlacmp bpute.data bpute.txt

	hla -@@ -thread -p:temp -obj:temp -x:bputr.exe bputr
	bputr.exe
	hlacmp bputr.data bputr.txt

	hla -@@ -thread -p:temp -obj:temp -x:bFile.exe bFile
	bFile.exe




	

clean:
	delete temp
	delete .inc
	delete .o
	delete .obj
	delete .link
	delete .exe
	delete .asm
	delete .txt
	delete .pdb
	delete .ilk
	