#all:
#	echo os_threads unit tests need to be written.

thread:
#	cp .../trunk/os_mac/temp/* temp
#	cp .../trunk/os_threads/temp/* temp
#	cp .../trunk/os_excepts/temp/* temp
#	cp .../trunk/args/temp/* temp
#	cp .../trunk/os_dependent/temp/* temp
	hla -@@ -sourcemode -p:temp -obj:temp -thread tThreads
	tThreads


clean:
	delete temp
	delete .o
	delete tThreads
	